### ISSUE TITLE
Tutorial 1 fails

### ISSUE THREAD

**Issue by thowell** [JuliaDiff/FiniteDiff.jl#101]
Hi!

The first example from the readme fails for me when using the SVector macro. I'm on Julia version 1.3.1 and haven't tried 1.4.0.

Something like this works:

function g(x) # out-of-place
  global fcalls += 1
  len_x = length(x)
  SVector{len_x}([handleleft(x,i) - 2*x[i] + handleright(x,i) for i in 1:len_x])
end

**Comment by ChrisRackauckas** [comment]
Thanks fixed up
