### ISSUE TITLE
Syntax for derivatives in specific directions

### ISSUE THREAD

**Issue by volkerkarle** [JuliaDiff/FiniteDiff.jl#149]
Hi, first let me thank you for this amazing package, using it heavily now. 

So I was thinking what would be the best practice to take specific derivatives. For instance, consider a function f(a,b,c), but I'd like to take the derivative only in one specific direction. Right now I'll write it as
```
∂(f,x) = FiniteDiff.finite_difference_gradient(f, x)

f(a,b,c) = a^2 + b^2 + c^2 # only example

function ∂f∂b(a,b,c)
    f2(b) = f(a,b,c)
    return ∂(f2,[b])
end
```

It would be cool to work with this in a more functional (i.e. closer to mathematical syntax) way. Maybe it's already possible, what are your suggestions?

Thanks! v.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiff/SparseDiffTools.jl has this as `jacvec`. `num_jacvec(f,x,[0.0,1.0,0.0])`

**Comment by volkerkarle** [comment]
OK Thanks, I'll look into it!
