### ISSUE TITLE
What does "multi point derivatives" mean?

### ISSUE THREAD

**Issue by gdalle** [JuliaDiff/FiniteDiff.jl#181]
I'm not sure I understand what this function does: https://docs.sciml.ai/FiniteDiff/stable/#Multi-Point-Derivatives

**Comment by ChrisRackauckas** [comment]
That's just a header? I'm not sure what you're pointing to since that's just a header for derivatives, gradients, and jacobians.

**Comment by gdalle** [comment]
Well no, in the docs the following list of headers exists:

- scalar derivatives
- "multi point derivatives"
- gradients
- jacobians
- hessians

The term derivative usually applies to a function $f: R \to R$, or more generally $R \to R^m$, but in any case it takes a scalar input point.
Reading "multi point derivative" I imagine we have to supply _several input points_ $x^{(1)},x^{(2)},x^{(3)}$ to this routine, and we get _several derivatives, one at each point_ $f'(x^{(1)}),f'(x^{(2)}),f'(x^{(3)})$.
The source code gives me confirmation of that, but for lack of docstrings I was a bit confused when only reading the docs.

https://github.com/JuliaDiff/FiniteDiff.jl/blob/be7777fce89bbebb776367b8233b907030bdfb7e/src/derivatives.jl#L71-L74

**Comment by gdalle** [comment]
<img width="312" alt="Screenshot 2024-03-09 at 16 15 47" src="https://github.com/JuliaDiff/FiniteDiff.jl/assets/22795598/6b110c32-3041-4bed-a4c3-8bd62d0d882b">

If "multi point derivatives" is intended to be one level lower than derivative, gradient, jacobian and hessian, then that will make it much clearer indeed. But the toc doesn't suggest it

**Comment by ChrisRackauckas** [comment]
It should just be multi-dimensional derivatives. I edited that already, and subsetting the header I thought was done already.

**Comment by gdalle** [comment]
Okay thanks. But that might be confusing for another reason: multi dimensional derivative evokes the idea of a function $f: R \to R^m$, where the derivative is a vector.

IIUC this section would be better off with the original name, or something like "multi input derivative", because is instead about several derivatives at different points of a function $f: R \to R$.

Instead, to get the derivative of $f: R \to R^m$ (which I would call "multi dimensional derivative"), we have to use `finite_difference_gradient`:

> Gradients are either a vector->scalar map f(x), or a scalar->vector map f(fx,x) if inplace=Val{true} and fx=f(x) if inplace=Val{false}.

**Comment by ChrisRackauckas** [comment]
I'm happy to consider any wording change you PR. Call it a partial derivative of a function with one variable, the total derivative optimized to the scalar input case, or whatnot. I'm happy to go with the words others consider easiest to understand, just write it out in full in a PR

**Comment by gdalle** [comment]
Will do, thanks, just wanted to make sure I understood what it was first 😊

**Comment by gdalle** [comment]
I decided to roll up my sleeves and make a proper documentation in the process. Now the multipoint derivative is clarified in the docstrings of #182, among other things
