### ISSUE TITLE
Documentation stuck on v2.20

### ISSUE THREAD

**Issue by gdalle** [JuliaDiff/FiniteDiff.jl#190]
Any idea why the documentation doesn't reflect the latest package version? Maybe an ill-configured TagBot or a missing GitHub token?

**Comment by ChrisRackauckas** [comment]
The keys look fine and nothing changed since they last ran, but nothing triggers release action runs. Yeah I'm not sure.

**Comment by gdalle** [comment]
For future reference, I solved it by re-pushing the last tag manually with a `+doc1` modified, as indicated here: https://documenter.juliadocs.org/stable/man/hosting/#Fixing-broken-release-deployments
