### ISSUE TITLE
Question about how to use on gpu

### ISSUE THREAD

**Issue by yolhan83** [JuliaDiff/FiniteDiff.jl#195]
Hello, I wonder why this is not working on gpu : 
```julia
julia> using CUDA,FiniteDiff
julia> f(x) = sum(abs2,x)
f (generic function with 1 method)

julia> x = rand(100,100) |> CuArray;

julia> f(x)
3298.8592709432687

julia> FiniteDiff.finite_difference_gradient(f,x);
ERROR: MethodError: no method matching compute_epsilon(::Val{:central}, ::CuArray{Float64, 2, CUDA.DeviceMemory}, ::Float64, ::Float64, ::Bool)
The function `compute_epsilon` exists, but no method is defined for this combination of argument types.

julia> FiniteDiff.finite_difference_gradient(f,collect(x)); # works
```

**Comment by ChrisRackauckas** [comment]
I don't currently have a GPU to debug this: can you share the full stack trace so I can see if I can eyeball it?

**Comment by ChrisRackauckas** [comment]
A new patch should come out in an hour. That should handle this. `compute_epsilon(fdtype, x, relstep, absstep, dir)` should've been `compute_epsilon(fdtype, one(eltype(x)), relstep, absstep, dir)`. I don't have a good way to test it, because you really only hit this with GPU arrays, but it's at least a clear typo so I put the patch out for now.

**Comment by yolhan83** [comment]
Thank you, the gradient pass now but is completly false,
```
 using CUDA,FiniteDiff,Zygote
f(x) = sum(abs2,x)/length(x)
x = (Float32[1 2;3 4]) |> CuArray;
display(FiniteDiff.finite_difference_gradient(f,x))
Zygote.gradient(f,x)[1]
```
results : 
```
2×2 CuArray{Float32, 2, CUDA.DeviceMemory}:
 -761.702  -761.453
 -761.202  -760.952
2×2 CuArray{Float32, 2, CUDA.DeviceMemory}:
 0.5  1.0
 1.5  2.0
```
It works fine when x is a vector but not when it is an array

**Comment by ChrisRackauckas** [comment]
@oscardssmith can you look into this? I don't have a GPU and it needs to look at the no-indexing GPU branches.
