### ISSUE TITLE
GradientCache typo?

### ISSUE THREAD

**Issue by anriseth** [JuliaDiff/FiniteDiff.jl#30]
The non-allocating `GradientCache` constructor has a line that calls `eltype(df)`, but I can't see `df` anywhere in the arguments list?

https://github.com/JuliaDiffEq/DiffEqDiffTools.jl/blob/master/src/gradients.jl#L57
https://github.com/JuliaDiffEq/DiffEqDiffTools.jl/blob/master/README.md#allocating-cache-constructor

@dextorious / @ChrisRackauckas

**Comment by anriseth** [comment]
I also think that the `c1` etc. should be passed on to `GradientCache` in these two functions. 
https://github.com/JuliaDiffEq/DiffEqDiffTools.jl/blob/master/src/gradients.jl#L108
https://github.com/JuliaDiffEq/DiffEqDiffTools.jl/blob/master/src/gradients.jl#L134

Or have I misunderstood something here?

**Comment by ChrisRackauckas** [comment]
Hmm, I made a change to `c1` but does it actually need to be required here?

**Comment by anriseth** [comment]
> Hmm, I made a change to c1 but does it actually need to be required here?


Thanks. There's also a reference to `df` on this line https://github.com/JuliaDiffEq/DiffEqDiffTools.jl/blob/master/src/gradients.jl#L72
I don't know what is needed and not, but it seems like a test calling the non-allocating GradientCache must be missing if the tests pass?

**Comment by ChrisRackauckas** [comment]
Yeah, the tests are using the allocating cache. That last one was created hastily at the end it needs fixing. Optim shouldn't require either though since it should have an empty cache for R^n -> R gradients.
