### ISSUE TITLE
`typeof(x)` where x is not defined in GradientCache

### ISSUE THREAD

**Issue by pkofod** [JuliaDiff/FiniteDiff.jl#46]
Am I blind, or is `x` not defined here? https://github.com/JuliaDiffEq/DiffEqDiffTools.jl/blob/4c51240b7576327f09710ff6ace5db044ca4cfdc/src/gradients.jl#L71

**Comment by dextorious** [comment]
Yup, that's a bug introduced by the last big API refactoring. The fact that it's survived this long means that not only did I forget to include a test for it, that entire constructor isn't used anywhere. I'll fix it when I get a chance, but unless you actually wanted to use this, it won't be my most urgent priority.

**Comment by pkofod** [comment]
> I'll fix it when I get a chance, but unless you actually wanted to use this, it won't be my most urgent priority.

this was just something noticed when reading the code, didn't encounter it in practice, so no big deal for me.
