### ISSUE TITLE
Real OOP path for differencing functions

### ISSUE THREAD

**Issue by kanav99** [JuliaDiff/FiniteDiff.jl#47]
MWE:
```julia
using OrdinaryDiffEq
function f(u,p,t)
	return 5*u
end
u0 = 1.0
tspan = (0.0,1.0)
prob = ODEProblem(f,u0,tspan)
sol = solve(prob, Rosenbrock23(;autodiff=false, diff_type=Val{:forward}))
```
We get error `no method matching similar(::Float64)` in the line: https://github.com/JuliaDiffEq/DiffEqDiffTools.jl/blob/master/src/gradients.jl#L127

**Comment by ChrisRackauckas** [comment]
Yes, these all don't have a non-mutating path yet, so anything with scalars and static arrays will fail. Ref:

https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/390
https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/373

**Comment by kanav99** [comment]
Similar problem was found here: https://github.com/JuliaDiffEq/DiffEqDiffTools.jl/blob/master/src/function_wrappers.jl#L16

**Comment by ChrisRackauckas** [comment]
We need a real OOP path for Hessians and Jacobians as well.
