### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by andreasnoack** [JuliaDiff/FiniteDiff.jl#82]
Currently, the input vectors are mutated to avoid allocations when computing finite difference gradients and Jacobians. This isn't thread safe when using the same input vector across multiple threads. It would be good to mention in the README or alternatively avoid the mutation.

**Comment by ChrisRackauckas** [comment]
You give it a cache of things to mutate, and it only mutates things in there. I thought that's pretty explicitly not going to be thread-safe and you need a cache per thread?

**Comment by andreasnoack** [comment]
I'm talking about https://github.com/JuliaDiffEq/DiffEqDiffTools.jl/blob/2fa19f467c5eff101d42860dfcc462273b9bbbe1/src/gradients.jl#L284
which is mutating the input vector `x`.

**Comment by ChrisRackauckas** [comment]
oh yes, forgot about that. We should just make the cache larger. O(n) memory is cheap in comparison to the Jacobian.

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/JuliaDiff/FiniteDiff.jl/pull/112
