### ISSUE TITLE
More general name

### ISSUE THREAD

**Issue by matthieugomez** [JuliaDiff/FiniteDiff.jl#83]
This library is now much more general than a backend for DifferentialEquations. 
Maybe it should be renamed to something that reflects this? Like DiffTools?

**Comment by ChrisRackauckas** [comment]
Yeah, I've thought about it. We should probably do it soon. It's just disruptive to do a name change.

**Comment by JeffreySarnoff** [comment]
We need a good way to deprecate an old package repository name in favor of new better-fitting name. One that allows the newly named repo to be active and used from the outset whilst the deprecated name is available as if it were symbolic github repo link, and it all play well with Pkg (or all lives in clever Pkg code realization).

**Comment by ChrisRackauckas** [comment]
We have a way to do that, and that's how we changed this one!

**Comment by matthieugomez** [comment]
Thanks!
