### ISSUE TITLE
Type piracy on `vec(::Number)`

### ISSUE THREAD

**Issue by oschulz** [JuliaDiff/FiniteDiff.jl#95]
FiniteDIff currently commits a bit of a (IMHO) monstrous type piracy here:

https://github.com/JuliaDiff/FiniteDiff.jl/blob/d7afba071daba72927c18d7ee6dc47bb14eac307/src/jacobians.jl#L127

```julia
function Base.vec(x::Number)
    x
end
```

The principal issue of piracy aside, this results in a conflict of FiniteDiff with it's former self, DiffEqDiffTools. I currently have that issue with a package configuration that pulls them both in, due to an older version of Optim. The result is

```
julia> using Optim, NLSolversBase
[ Info: Precompiling Optim [429524aa-4258-5aef-a3af-852621145aeb]
WARNING: Method definition vec(Number) in module FiniteDiff at /user/.julia/packages/FiniteDiff/IPtYL/src/jacobians.jl:128 overwritten in module DiffEqDiffTools at /user/.julia/packages/DiffEqDiffTools/3mm8U/src/jacobians.jl:114.
  ** incremental compilation may be fatally broken for this module **
```

**Comment by ChrisRackauckas** [comment]
This is already fixed in the most up to date version of NLSolversBase and Optim right @pkofod ?

**Comment by oschulz** [comment]
With a current Optim, there's no problem, I think, I was just stuck on an older version for an application (not any longer now, I hope).

I mainly was surprised to encounter that `vec(::Number)` definition ...

**Comment by oschulz** [comment]
... isn't that kinda frowned upon? :-)

**Comment by ChrisRackauckas** [comment]
No, because it should be added to Base, so I'm just helping 👍

**Comment by oschulz** [comment]
Lol, yes, I was actually wondering about that (whether it shouldn't be in Base, then). Though there may be some discussion over the semantics ... ;-)

**Comment by ChrisRackauckas** [comment]
This'll get upstreamed soon enough. A few people know about this already.

**Comment by oschulz** [comment]
Ah, right - I should have known. :-) Sorry for the noise.
